### ISSUE TITLE
GET without erasing information.

### ISSUE THREAD

**Issue by vinimyls** [tdv/redis-cpp#15]
I'm running the setget example program setget, however for my application i need to do the GET without erasing the redis information. To delete I must do this by the "DEL" command or clean via "FLUSHDB"

**Comment by tdv** [comment]
Hi. You can use GET with a timeout and the information will have automatically deleted at the end of the timeout. There are enough other ways how to do that. Redis provides enough and more than enough commands including writing the lua scripts like a command (https://redis.io/commands). Redis has enough branched out command list for many cases.

The library provides low-level access in order to be more convenient to execute the commands within C++.

Hopefully, it'll solve your issue.
