### ISSUE TITLE
how to execute rpush

### ISSUE THREAD

**Issue by rahulsharma11** [tdv/redis-cpp#20]
Hi,
How can i use the redis utilities in pubsub application here like rpush/get/set etc?

Thanks

**Comment by rahulsharma11** [comment]
Hi @tdv ,
Just to update - i am able to run rpush, but not able to run lrange command.
Any suggestion?

**Comment by tdv** [comment]
Hi.

Please, add a bit code that reflects and emphasizes your problem and, hopefully, I'll help you with the library usage in order to solve your issue.

In regards, I'll notice, like many times before in other issues mentioned early, the library provides only a low-level access having covered only the protocol and there are no other additional features that are not available out of the box in Redis.

Regards.

**Comment by rahulsharma11** [comment]
Ok,
Thanks for the information.
