### ISSUE TITLE
More connection parameters

### ISSUE THREAD

**Issue by SanPen** [tdv/redis-cpp#22]
Hi!

I've seen that the connection function does not have password into it

i.e.: 
```
auto stream = rediscpp::make_stream("localhost", "6379");
```

Is there any way to define the password of the connection?

**Comment by tdv** [comment]
Hi. 

The function make_stream establishes only a TCP connection having wrapped the one like a IO stream from std library.

Sorry, I'm not familiar with whether it is possible or not to use a password to open a connection to Redis.

In my implementation I've wrapped the work with a network via boost library and have represented that like std::iostream. The common idea of the implementation is to implement everything you've needed having only basic implementation out of the box.

Redis uses quite simple text protocol and having sent std::cout like a stream in another function from the library you'll see on the screen how it works and which particular command has been sent.
That commands you can use later having opened a connection via telnet at least in order to check their and get known better how it works in whole.

If you find an approach how to establish the connection with password to Redis, please share that. I'll be really appreciated you.

Good luck.

Regards
Dmitry
