### ISSUE TITLE
Alternative Redis client proposed for inclusion in Boost

### ISSUE THREAD

**Issue by mzimbres** [tdv/redis-cpp#26]
Sorry for opening an issue for this, I did not find any better means of contacting you.

I would like to invite your community to write a review for an alternative Redis client library that is being proposed for inclusion in boost. As the author of a redis client yourself your opinion would be highly valuable. For more information see https://lists.boost.org/Archives/boost/2023/01/253871.php.

Thanks

**Comment by tdv** [comment]
Hello.
The contacts are not hidden. If you take a look through any header or source file of the library, you'll notice my email there. Furthermore, the email below my photo in profile (in a bit vague form, in order to avoid robot's email grabbing). I have familiarized myself with the review steps and rules. Email me via tkachenkodmitryv@gmail.com with a short list I could do for the review and I'll.
Regards.
