### ISSUE TITLE
'Scan' function type response std::bad_cast issue

### ISSUE THREAD

**Issue by WildBoarGonnaGo** [tdv/redis-cpp#29]
Hello, I have no idea how to work with 'scan' functions. For example, when I'm trying to run the following code

```
auto response = rediscpp::execute(*stream, "scard", "some_set");
std::cout << response.as_integer() << std::endl;
// Output is '4'
response = rediscpp::execute(*stream, "sscan", "some_set", "0");
std::cout << std::boolalpha << response.is_array() << std::endl;
// Output is 'true'
auto vec = response.as_string_array();
// 'bad_cast' error
```

the last line causes `std::bad_cast` error, though `response.is_array()` is true. Furthermore, any available rediscpp cast causes `std::bad_cast` error. Am i doing something wrong?  Is there any way to avoid this error?

**Comment by tdv** [comment]
Hi, I'm so sorry; I've just noticed the message. The library is a low-level tool for sending commands and receiving responses. There isn't any type checking for a specific command. It might be a good idea to write a new library with commands, but I stopped at this version, which satisfied my needs some years ago and has proven quite useful for others through usage.

After reading about your issue, I'd suggest using the approach for working with arrays in a similar way to the examples in the library. This is because "SCAN" (and similar commands) return complex arrays: the first part contains additional information, and the second part is an array with the data. In this case, you can extract data using a couple of nested visitors, as described in the "SCAN" command documentation and the library's examples.

SCAN: https://redis.io/commands/scan/
Examples
1. https://github.com/tdv/redis-cpp/blob/master/examples/pubsub/src/main.cpp#L58
2. https://github.com/tdv/redis-cpp/blob/master/examples/resp/src/main.cpp#L38
